3rd World- Genre ENT.
Interested and dedicating, to the underground movements, across the board. 
All artists are welcome for collaboration, so long as standards are met,
not all standards invoked by sole proprietor,or <third-partyname I@:alias I@>
 .github/workflows/blank.yml
on: [push]
@
jobs:
  build:third-partyname I@:alias I@
 .github/workflows/blank.yml

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
https://github.com/VerryImportantAsset/lati-root.git

-name@@lucho-bangs -1,21 +1,23 @@
"Date of node"'01_13_2020'.# lati-root
Labguanges in relation to latin,=root
+source_code node from root traces in computer language=
+latin_source node from langauge=lab
Generally intentional project to re inovate possobilty over probability
Inturn makes an unturn resource fragment to communicate with perhaps maybe one day
=AI responsiveness to human gesture generally speaking from statistical Data already aquired
By AMI bytes.(Artaficial Memory Intention)
+Later to be implemented by VIA(R)'s SECURITY PROTOCOL VIAGCPLLC (still in pre-alpha) Data accumilation
Set to no specific time schedule due to sponsor,support,or funds to continue this project.
End;'VIACODE'#"lati-root"_now
+'To be continued'+"date of new node"'-------'.#
-'Owner and founder' of -VIA; -NAME I:-('eliuth lopez')
-ALIAS I; for -NAME I:-('lucho-bangs')
-CEO of -VIA; -NAME I:-('eloy lopez .jr')
