name: Lucho-bangs
on:2020
  schedule:2021
  - cron: "0 0 * * *"

jobs:2021

    runs-on: ubuntu-latest

    steps:
    - uses: actions/work@v1
      with:
        }
        Package-Bo9t-message: 'Stale issue message'https://github.com/VerryImportantAsset/lati-root.git
        Package-pr-automate: 'Stale pull request message'3rd World- Genre ENT. Grey5six@gmail.com Interested and dedicating, to the underground movements, across the board.  All artists are welcome for collaboration, so long as standards are met,not all standards invoked by sole proprietor,or third-party
       
sudo apt-get install -y postfix

sudo apt-get install curl openssh-server ca-certificates apt-transport-https
curl https://packages.gitlab.com/gpg.key | sudo apt-key add -


sudo EXTERNAL_URL="https://github.com/ lucho-bangs" apt-get install gitlab-ce

sudo curl -sS https://packages.gitlab.com/install/repositories/gitlab/raspberry-pi2/script.deb.sh | sudo bash

